import ts from "typescript";
import type { CompileError, CompileOptions } from "../index.js";
import type { TypedAST } from "../checker/index.js";
import { analyzeSource } from "../checker/index.js";
import { generateModule } from "../codegen/index.js";
import { emitObject } from "../emit/object.js";
import { preprocessImports } from "../import-resolver.js";
import type { WasmModule, ValType, Instr } from "../ir/types.js";
import { generateCHeader, extractCHeaderExports } from "../emit/c-header.js";
import type { CabiExportInfo, ParamDef } from "../codegen-linear/c-abi.js";
import { mapParamsToCabi, mapResultToCabi, emitCabiWrappers } from "../codegen-linear/c-abi.js";
import { hasExportModifier, pushSourceAnchoredDiagnostic } from "./validation.js";
import { DOWNGRADE_DIAG_CODES } from "./import-manifest.js";
import { buildImportManifest } from "./import-manifest.js";

/**
 * Apply C ABI transformation to a compiled WasmModule.
 * Rewrites exported function signatures for C compatibility and generates a C header.
 */
function applyCabiTransform(mod: WasmModule, moduleName: string): { cHeader: string } {
  const numImportFuncs = mod.imports.filter((i) => i.desc.kind === "func").length;

  // Build CabiExportInfo for each exported function
  const exportInfos: CabiExportInfo[] = [];
  for (const exp of mod.exports) {
    if (exp.desc.kind !== "func") continue;
    if (exp.name === "memory") continue;

    const funcIdx = exp.desc.index;
    const localIdx = funcIdx - numImportFuncs;
    if (localIdx < 0 || localIdx >= mod.functions.length) continue;

    const func = mod.functions[localIdx];
    const typeDef = mod.types[func.typeIdx];
    if (!typeDef || typeDef.kind !== "func") continue;

    // Build ParamDefs from the function type
    // In linear memory mode: f64 = number, i32 = pointer (string/array/object)
    // We infer semantics from the function name and wasm types
    const paramDefs: ParamDef[] = typeDef.params.map((wt, i) => {
      // Without TS type info at this stage, we infer from wasm types:
      // f64 → number, i32 → could be string/array/object/boolean
      // For now, treat all i32 params as direct (caller provides i32)
      const semantic = wt.kind === "f64" ? ("number_f64" as const) : ("number_i32" as const);
      return { name: `p${i}`, wasmType: wt, semantic };
    });

    const cabiParams = mapParamsToCabi(paramDefs);
    const resultSemantic =
      typeDef.results.length === 0
        ? ("void" as const)
        : typeDef.results[0].kind === "f64"
          ? ("number_f64" as const)
          : ("number_i32" as const);
    const cabiResult = mapResultToCabi(typeDef.results.length > 0 ? typeDef.results[0] : null, resultSemantic);

    const cabiName = exp.name; // mangleCabiName is identity for simple names

    exportInfos.push({
      tsName: exp.name,
      cabiName,
      params: cabiParams,
      result: cabiResult,
    });
  }

  // Apply wrappers for functions that need them
  emitCabiWrappers(mod, exportInfos);

  // Generate C header from the final module state
  const headerExports = extractCHeaderExports(mod);
  const cHeader = generateCHeader(moduleName, headerExports);

  return { cHeader };
}

// ── .d.ts generation ─────────────────────────────────────────────────

function generateDts(ast: TypedAST, mod: WasmModule): string {
  const lines: string[] = ["// Generated by js2wasm", ""];

  // Exports interface
  const exportLines: string[] = [];
  for (const stmt of ast.sourceFile.statements) {
    if (ts.isFunctionDeclaration(stmt) && stmt.name && hasExportModifier(stmt)) {
      const name = stmt.name.text;
      const isAsync = mod.asyncFunctions.has(name);
      const params = stmt.parameters
        .map((p) => {
          const paramName = ts.isIdentifier(p.name) ? p.name.text : "_";
          const typeText = mapTypeForDts(p.type, ast.sourceFile);
          const optional = p.questionToken ? "?" : "";
          return `${paramName}${optional}: ${typeText}`;
        })
        .join(", ");
      let returnType = mapTypeForDts(stmt.type, ast.sourceFile);
      // For async functions, preserve the Promise<T> wrapper in the .d.ts output
      if (isAsync && !returnType.startsWith("Promise<")) {
        returnType = `Promise<${returnType}>`;
      }
      exportLines.push(`  ${name}(${params}): ${returnType};`);
    }
  }

  if (exportLines.length > 0) {
    lines.push(
      ...exportLines.map((l) => {
        // Convert "  name(params): ret;" to "export declare function name(params): ret;"
        const m = l.match(/^\s+(\w+)\(([^)]*)\):\s*(.+);$/);
        if (m) return `export declare function ${m[1]}(${m[2]}): ${m[3]};`;
        return l;
      }),
    );
    lines.push("");
  }

  return lines.join("\n");
}

// ── Imports helper generation ────────────────────────────────────────

function generateImportsHelper(mod: WasmModule): string {
  const manifest = buildImportManifest(mod);
  const manifestJson = JSON.stringify(manifest, null, 2);
  const stringPoolJson = JSON.stringify(mod.stringPool, null, 2);

  return [
    "// Generated by js2wasm — shared runtime imports helper",
    "// Shared host glue comes from the js2wasm runtime so it only needs to ship once.",
    '// Usage: import { createImports, instantiateBytes, instantiateFromUrl } from "./module.imports.js";',
    "",
    'import { buildImports, instantiateWasm, instantiateWasmStreaming } from "js2wasm";',
    "",
    `const manifest = ${manifestJson};`,
    `const stringPool = ${stringPoolJson};`,
    "",
    "export function createImports(deps, options) {",
    "  return buildImports(manifest, deps, stringPool, options);",
    "}",
    "",
    "export async function instantiateBytes(wasmBytes, deps, options) {",
    "  const imports = createImports(deps, options);",
    "  const result = await instantiateWasm(wasmBytes, imports.env, imports.string_constants);",
    "  if (imports.setExports) imports.setExports(result.instance.exports);",
    "  return { ...result, imports };",
    "}",
    "",
    "export async function instantiateFromResponse(response, deps, options) {",
    "  const imports = createImports(deps, options);",
    "  const result = await instantiateWasmStreaming(response, imports.env, imports.string_constants);",
    "  if (imports.setExports) imports.setExports(result.instance.exports);",
    "  return { ...result, imports };",
    "}",
    "",
    "export async function instantiateFromUrl(url, deps, options) {",
    "  return instantiateFromResponse(fetch(url), deps, options);",
    "}",
    "",
  ].join("\n");
}

function generateEnvImportLine(name: string, mod: WasmModule): string {
  // String literal thunks
  const strValue = mod.stringLiteralValues.get(name);
  if (strValue !== undefined) {
    return `${name}: () => ${JSON.stringify(strValue)}`;
  }

  // Console stubs (log, warn, error)
  for (const cm of ["log", "warn", "error"]) {
    if (name === `console_${cm}_number`) return `console_${cm}_number: (v) => console.${cm}(v)`;
    if (name === `console_${cm}_bool`) return `console_${cm}_bool: (v) => console.${cm}(Boolean(v))`;
    if (name === `console_${cm}_string`) return `console_${cm}_string: (v) => console.${cm}(v)`;
    if (name === `console_${cm}_externref`) return `console_${cm}_externref: (v) => console.${cm}(v)`;
  }

  // Primitive method imports
  if (name === "number_toString") return "number_toString: (v) => String(v)";

  // String compare (lexicographic ordering)
  if (name === "string_compare") return "string_compare: (a, b) => (a < b ? -1 : a > b ? 1 : 0)";

  // String method imports
  if (name.startsWith("string_")) {
    const method = name.slice(7);
    return `${name}: (s, ...a) => s.${method}(...a)`;
  }

  // String.fromCharCode
  if (name === "String_fromCharCode") return "String_fromCharCode: (code) => String.fromCharCode(code)";

  // ToUint32 helper for Math.clz32/imul
  if (name === "__toUint32") return "__toUint32: (x) => x >>> 0";

  // Math host imports
  if (name.startsWith("Math_")) {
    const method = name.slice(5);
    return `${name}: Math.${method}`;
  }

  // Extern class imports
  for (const ec of mod.externClasses) {
    const prefix = ec.importPrefix;
    const nsAccess = ec.namespacePath.length > 0 ? `deps.${ec.namespacePath.join(".")}` : `deps`;

    if (name === `${prefix}_new`) {
      const paramList = ec.constructorParams.map((_, i) => `a${i}`).join(", ");
      return `${name}: (${paramList}) => new ${nsAccess}.${ec.className}(${paramList})`;
    }
    for (const [methodName, sig] of ec.methods) {
      if (name === `${prefix}_${methodName}`) {
        const paramList = sig.params
          .slice(1)
          .map((_, i) => `a${i}`)
          .join(", ");
        return `${name}: (self${paramList ? ", " + paramList : ""}) => self.${methodName}(${paramList})`;
      }
    }
    for (const [propName, propInfo] of ec.properties) {
      if (name === `${prefix}_get_${propName}`) {
        return `${name}: (self) => self.${propName}`;
      }
      if (name === `${prefix}_set_${propName}`) {
        return `${name}: (self, v) => { self.${propName} = v; }`;
      }
    }
  }

  // __make_callback: late-binding wrapper
  if (name === "__make_callback") {
    return `${name}: (id, cap) => (...args) => wasmExports[\`__cb_\${id}\`](cap, ...args)`;
  }

  // Async/await support: __await is identity (host functions are sync from Wasm's perspective)
  if (name === "__await") return `${name}: (v) => v`;

  // Generator support
  if (name === "__gen_create_buffer") return `${name}: () => []`;
  if (name === "__gen_push_f64") return `${name}: (buf, v) => { buf.push(v); }`;
  if (name === "__gen_push_i32") return `${name}: (buf, v) => { buf.push(v); }`;
  if (name === "__gen_push_ref") return `${name}: (buf, v) => { buf.push(v); }`;
  if (name === "__create_generator")
    return `${name}: (buf, pendingThrow) => { let i = 0; return { next() { if (i < buf.length) return { value: buf[i++], done: false }; if (pendingThrow !== null && pendingThrow !== undefined) { const e = pendingThrow; pendingThrow = null; throw e; } return { value: undefined, done: true }; }, return(v) { i = buf.length; return { value: v, done: true }; }, throw(e) { i = buf.length; throw e; }, [Symbol.iterator]() { return this; } }; }`;
  if (name === "__create_async_generator")
    return `${name}: (buf, pendingThrow) => { let i = 0; function mkR(v, d) { const p = { value: v, done: d }; return { value: v, done: d, then(res, rej) { return Promise.resolve(p).then(res, rej); } }; } function mkE(e) { return { done: true, value: undefined, then(res, rej) { return Promise.reject(e).then(res, rej); } }; } return { next() { if (i < buf.length) return mkR(buf[i++], false); if (pendingThrow !== null && pendingThrow !== undefined) { const e = pendingThrow; pendingThrow = null; return mkE(e); } return mkR(undefined, true); }, return(v) { i = buf.length; return mkR(v, true); }, throw(e) { i = buf.length; return mkE(e); }, [Symbol.asyncIterator]() { return this; } }; }`;
  if (name === "__gen_next") return `${name}: (gen) => gen.next()`;
  if (name === "__gen_result_value") return `${name}: (r) => r.value`;
  if (name === "__gen_result_value_f64") return `${name}: (r) => Number(r.value)`;
  if (name === "__gen_result_done") return `${name}: (r) => r.done ? 1 : 0`;

  // Union type helper imports
  if (name === "__typeof_number") return `${name}: (v) => typeof v === "number" ? 1 : 0`;
  if (name === "__typeof_string") return `${name}: (v) => typeof v === "string" ? 1 : 0`;
  if (name === "__typeof_boolean") return `${name}: (v) => typeof v === "boolean" ? 1 : 0`;
  if (name === "__typeof_undefined") return `${name}: (v) => typeof v === "undefined" ? 1 : 0`;
  if (name === "__typeof_object") return `${name}: (v) => typeof v === "object" ? 1 : 0`;
  if (name === "__typeof_function") return `${name}: (v) => typeof v === "function" ? 1 : 0`;
  if (name === "__unbox_number") return `${name}: (v) => Number(v)`;
  if (name === "__unbox_boolean") return `${name}: (v) => v ? 1 : 0`;
  if (name === "__box_number") return `${name}: (v) => v`;
  if (name === "__box_boolean") return `${name}: (v) => Boolean(v)`;
  if (name === "__box_symbol")
    return `${name}: (() => { const c = new Map([[1,Symbol.iterator],[2,Symbol.hasInstance],[3,Symbol.toPrimitive],[4,Symbol.toStringTag],[5,Symbol.species],[6,Symbol.isConcatSpreadable],[7,Symbol.match],[8,Symbol.replace],[9,Symbol.search],[10,Symbol.split],[11,Symbol.unscopables],[12,Symbol.asyncIterator]]); return (id) => { let s = c.get(id); if (!s) { s = Symbol("wasm_"+id); c.set(id, s); } return s; }; })()`;
  if (name === "__is_truthy") return `${name}: (v) => v ? 1 : 0`;
  if (name === "__typeof") return `${name}: (v) => typeof v`;

  // Callback bridges for functional array methods
  if (name === "__call_1_f64") return `${name}: (fn, a) => fn(a)`;
  if (name === "__call_2_f64") return `${name}: (fn, a, b) => fn(a, b)`;

  // Fallback: no-op stub
  return `${name}: () => {}`;
}

function mapTypeForDts(typeNode: ts.TypeNode | undefined, sf: ts.SourceFile): string {
  if (!typeNode) return "void";
  const text = typeNode.getText(sf);
  if (text === "number" || text === "boolean" || text === "string" || text === "void") {
    return text;
  }
  // Handle Promise<T> type references
  if (ts.isTypeReferenceNode(typeNode)) {
    const typeName = typeNode.typeName.getText(sf);
    if (typeName === "Promise" && typeNode.typeArguments?.length === 1) {
      const innerType = mapTypeForDts(typeNode.typeArguments[0], sf);
      return `Promise<${innerType}>`;
    }
  }
  return "any";
}

// ── Object file compilation ─────────────────────────────────────────

export interface ObjectCompileResult {
  /** Relocatable Wasm object file (.o) */
  object: Uint8Array;
  /** true if compilation was successful */
  success: boolean;
  /** Error messages with line numbers */
  errors: CompileError[];
}

/**
 * Compile TypeScript source to a relocatable Wasm object file (.o).
 * Uses the same pipeline as compileSource but emits LLVM-style
 * linking metadata instead of a final executable module.
 */
export function compileToObjectSource(source: string, options: CompileOptions = {}): ObjectCompileResult {
  const errors: CompileError[] = [];

  const processedSource = preprocessImports(source);
  const defaultFileName = options.fileName ?? (options.allowJs ? "input.js" : "input.ts");
  const effectiveFileName = options.moduleName ?? defaultFileName;
  const ast = analyzeSource(processedSource, effectiveFileName, { allowJs: options.allowJs });

  for (const diag of ast.diagnostics) {
    if (diag.category === 1) {
      const pos = diag.file ? diag.file.getLineAndCharacterOfPosition(diag.start ?? 0) : { line: 0, character: 0 };
      const severity = DOWNGRADE_DIAG_CODES.has(diag.code) ? "warning" : "error";
      errors.push({
        message: typeof diag.messageText === "string" ? diag.messageText : diag.messageText.messageText,
        line: pos.line + 1,
        column: pos.character + 1,
        severity: severity as "error" | "warning",
        code: diag.code,
      });
    }
  }

  const TOLERATED_SYNTAX_CODES = new Set([
    1156, // "'let' declarations can only be declared inside a block"
    1313, // "The body of an 'if' statement cannot be the empty statement"
    1344, // "A label is not allowed here"
    1182, // "A destructuring declaration must have an initializer"
    1228, // "A type predicate is only allowed in return type position"
    1163, // "A 'yield' expression is only allowed in a generator body"
    1206, // "Decorators are not valid here"
    1207, // "Decorators cannot be applied to multiple get/set accessors"
    1435, // "Unknown keyword or identifier. Did you mean 'X'?" — yield in nested generator contexts (#521)
    1436, // "Decorators must precede the name and all keywords of property declarations"
    1486, // "Decorator used before 'export' here"
    1497, // "Expression must be enclosed in parentheses to be used as a decorator"
    1498, // "Invalid syntax in decorator"
    8038, // "Decorators may not appear after 'export' or 'export default'"
    1184, // "Modifiers cannot appear here" (#537)
    1109, // "Expression expected" (#537)
    1135, // "Argument expression expected" (#537)
    1262, // "Identifier expected. 'X' is a reserved word at the top-level of a module" (#537)
    1503, // "This regular expression flag is only available when targeting 'es2024'" (#654)
    1232, // "An import declaration can only be used at the top level of a namespace or module" (#654)
  ]);
  const hasSyntaxErrors = ast.syntacticDiagnostics.some(
    (d) => d.category === 1 && d.file === ast.sourceFile && !TOLERATED_SYNTAX_CODES.has(d.code),
  );

  if (hasSyntaxErrors && errors.length > 0) {
    return { object: new Uint8Array(0), success: false, errors };
  }

  let mod;
  try {
    const result = generateModule(ast);
    mod = result.module;
    for (const err of result.errors) {
      errors.push({
        message: err.message,
        line: err.line,
        column: err.column,
        severity: "error",
      });
    }
    if (result.errors.some((err) => err.message.startsWith("Codegen error:"))) {
      return { object: new Uint8Array(0), success: false, errors };
    }
  } catch (e) {
    pushSourceAnchoredDiagnostic(
      errors,
      ast.sourceFile,
      `Codegen error: ${e instanceof Error ? e.message : String(e)}`,
      "error",
    );
    return { object: new Uint8Array(0), success: false, errors };
  }

  let object: Uint8Array;
  try {
    object = emitObject(mod);
  } catch (e) {
    pushSourceAnchoredDiagnostic(
      errors,
      ast.sourceFile,
      `Object emit error: ${e instanceof Error ? e.message : String(e)}`,
      "error",
    );
    return { object: new Uint8Array(0), success: false, errors };
  }

  return { object, success: true, errors };
}

/**
 * Post-processing pass: widen all non-defaultable `ref` types to `ref_null`
 * throughout the module. This fixes two classes of Wasm validation errors:
 *
 * 1. "uninitialized non-defaultable local" -- locals with `ref $T` type have
 *    no implicit default value, so any code path that reads them before writing
 *    causes a validation error. Widening to `ref null $T` gives them a null default.
 *
 * 2. "struct.get/set expected type (ref null N), found ..." -- when function
 *    signatures use `ref` but callers/callees produce `ref_null` (or vice versa),
 *    the Wasm validator rejects the type mismatch. Consistently using `ref_null`
 *    in function types, locals, and globals avoids this.
 */
function widenNonDefaultableTypes(mod: WasmModule): void {
  function widenValType(t: ValType): ValType {
    return t.kind === "ref" ? { kind: "ref_null", typeIdx: t.typeIdx } : t;
  }

  // Widen all type definitions (func types, struct fields, array elements)
  function widenTypeDef(typeDef: (typeof mod.types)[number]): void {
    switch (typeDef.kind) {
      case "func":
        for (let i = 0; i < typeDef.params.length; i++) {
          typeDef.params[i] = widenValType(typeDef.params[i]!);
        }
        for (let i = 0; i < typeDef.results.length; i++) {
          typeDef.results[i] = widenValType(typeDef.results[i]!);
        }
        break;
      case "struct":
        for (const field of typeDef.fields) {
          field.type = widenValType(field.type);
        }
        break;
      case "array":
        typeDef.element = widenValType(typeDef.element);
        break;
      case "rec":
        for (const inner of typeDef.types) {
          widenTypeDef(inner);
        }
        break;
      case "sub":
        widenTypeDef(typeDef.type);
        break;
    }
  }

  for (const typeDef of mod.types) {
    widenTypeDef(typeDef);
  }

  // Widen function locals and block types in bodies
  for (const func of mod.functions) {
    for (const local of func.locals) {
      local.type = widenValType(local.type);
    }
    // Widen block types (if/block/loop/try) in instruction bodies
    widenBlockTypesInBody(func.body, widenValType);
  }

  // Widen global types
  for (const global of mod.globals) {
    global.type = widenValType(global.type);
  }

  // Widen import desc type for non-func imports (globals)
  for (const imp of mod.imports) {
    if (imp.desc.kind === "global") {
      imp.desc.type = widenValType(imp.desc.type);
    }
  }
}

/**
 * Recursively walk an instruction body and widen block types (if/block/loop/try)
 * from `ref` to `ref_null`, matching the widened function type signatures.
 */
function widenBlockTypesInBody(body: Instr[], widenValType: (t: ValType) => ValType): void {
  for (const instr of body) {
    const a = instr as any;
    // Widen block type if it's a val type with ref kind
    if (a.blockType && a.blockType.kind === "val") {
      a.blockType.type = widenValType(a.blockType.type);
    }
    // Recurse into nested instruction arrays
    if (a.then) widenBlockTypesInBody(a.then, widenValType);
    if (a.else) widenBlockTypesInBody(a.else, widenValType);
    if (a.body && Array.isArray(a.body)) widenBlockTypesInBody(a.body, widenValType);
    if (a.catches) {
      for (const c of a.catches) {
        if (c.body) widenBlockTypesInBody(c.body, widenValType);
      }
    }
    if (a.catchAll) widenBlockTypesInBody(a.catchAll, widenValType);
  }
}

export { applyCabiTransform, generateDts, generateImportsHelper, widenNonDefaultableTypes, widenBlockTypesInBody };
