/**
 * Compiler worker — uses pre-bundled compiler JS.
 * No tsx/loader needed. Bundle generated by: npx esbuild src/index.ts --bundle --platform=node --format=esm --outfile=scripts/compiler-bundle.mjs --external:typescript
 *
 * Uses incremental compilation via TS Language Service to cache parsed lib files
 * across compilations. First compilation is cold (~normal speed), subsequent ones
 * skip lib re-parsing for a significant speedup.
 */
import { parentPort } from "node:worker_threads";
import { compile, createIncrementalCompiler } from "./compiler-bundle.mjs";

let compileCount = 0;
const MAX_COMPILATIONS = 500; // Restart worker every 500 compilations to prevent state accumulation

// Incremental compiler — reuses parsed lib SourceFiles via oldProgram.
// Fresh checker per compilation (no state leakage), cached lib parses (fast).
let incrementalCompiler = null;
try {
  incrementalCompiler = createIncrementalCompiler({
    fileName: "test.ts",
    sourceMap: true,
    sourceMapUrl: "test.wasm.map",
    emitWat: false,
    skipSemanticDiagnostics: true,
  });
} catch (e) {
  // Fall back to non-incremental if creation fails
}

parentPort.on("message", (msg) => {
  const start = performance.now();
  try {
    const compileFn = incrementalCompiler ? incrementalCompiler.compile : compile;
    const result = incrementalCompiler
      ? compileFn(msg.source, {
          sourceMapUrl: msg.sourceMapUrl || "test.wasm.map",
        })
      : compile(msg.source, {
          fileName: "test.ts",
          sourceMap: true,
          sourceMapUrl: msg.sourceMapUrl || "test.wasm.map",
          emitWat: false,
          skipSemanticDiagnostics: true,
        });
    const compileMs = performance.now() - start;

    if (!result.success || result.errors.some(e => e.severity === "error")) {
      const errMsg = result.errors
        .filter(e => e.severity === "error")
        .map(e => `L${e.line}:${e.column} ${e.message}`)
        .join("; ");
      // Include TS diagnostic codes for early error detection
      const errorCodes = result.errors
        .filter(e => e.severity === "error" && e.code)
        .map(e => e.code);
      parentPort.postMessage({ id: msg.id, ok: false, error: errMsg || "unknown", errorCodes, compileMs });
      return;
    }

    parentPort.postMessage({
      id: msg.id,
      ok: true,
      binary: result.binary,
      stringPool: result.stringPool,
      imports: result.imports,
      sourceMap: result.sourceMap || null,
      compileMs,
    });
  } catch (err) {
    parentPort.postMessage({
      id: msg.id,
      ok: false,
      error: err.message || String(err),
      compileMs: performance.now() - start,
    });
  }

  compileCount++;
  // Restart worker periodically to prevent TS compiler state accumulation
  if (compileCount >= MAX_COMPILATIONS) {
    process.exit(0);
  }
});

parentPort.postMessage({ type: "ready", pid: process.pid });
