/**
 * Compiler worker — uses pre-bundled compiler JS.
 * No tsx/loader needed. Bundle generated by: npx esbuild src/index.ts --bundle --platform=node --format=esm --outfile=scripts/compiler-bundle.mjs --external:typescript
 */
import { parentPort } from "node:worker_threads";
import { compile } from "./compiler-bundle.mjs";

let compileCount = 0;
const MAX_COMPILATIONS = 200; // Restart worker every 200 compilations to limit memory accumulation

parentPort.on("message", (msg) => {
  const start = performance.now();
  try {
    const result = compile(msg.source, {
      fileName: "test.ts",
      sourceMap: true,
      sourceMapUrl: msg.sourceMapUrl || "test.wasm.map",
      emitWat: false,
      skipSemanticDiagnostics: true,

    });
    const compileMs = performance.now() - start;

    if (!result.success || result.errors.some(e => e.severity === "error")) {
      const errMsg = result.errors
        .filter(e => e.severity === "error")
        .map(e => `L${e.line}:${e.column} ${e.message}`)
        .join("; ");
      parentPort.postMessage({ id: msg.id, ok: false, error: errMsg || "unknown", compileMs });
      return;
    }

    parentPort.postMessage({
      id: msg.id,
      ok: true,
      binary: result.binary,
      stringPool: result.stringPool,
      imports: result.imports,
      sourceMap: result.sourceMap || null,
      compileMs,
    });
  } catch (err) {
    parentPort.postMessage({
      id: msg.id,
      ok: false,
      error: err.message || String(err),
      compileMs: performance.now() - start,
    });
  }

  compileCount++;
  // Restart worker periodically to prevent TS compiler state accumulation
  if (compileCount >= MAX_COMPILATIONS) {
    process.exit(0);
  }
});

parentPort.postMessage({ type: "ready", pid: process.pid });
