import ts from "typescript";
import { analyzeSource, type TypedAST } from "./checker/index.js";
import { generateModule } from "./codegen/index.js";
import { emitBinary } from "./emit/binary.js";
import { emitWat } from "./emit/wat.js";
import { preprocessImports } from "./import-resolver.js";
import type {
  CompileResult,
  CompileError,
  CompileOptions,
} from "./index.js";
import type { WasmModule, FuncTypeDef, ValType, ExternClassMeta } from "./ir/types.js";

/**
 * Orchestrates the full compilation pipeline:
 * TS Source → tsc Parser+Checker → Codegen → Binary + WAT
 */
export function compileSource(
  source: string,
  options: CompileOptions = {},
): CompileResult {
  const errors: CompileError[] = [];
  const emitWatOutput = options.emitWat !== false;

  // Step 0: Pre-process imports (replace import * as X with declare namespace)
  const processedSource = preprocessImports(source);

  // Step 1: Parse and type-check
  const ast = analyzeSource(processedSource, options.moduleName ?? "input.ts");

  // Collect TS diagnostics as errors
  for (const diag of ast.diagnostics) {
    if (diag.category === 1) {
      // Error
      const pos = diag.file
        ? diag.file.getLineAndCharacterOfPosition(diag.start ?? 0)
        : { line: 0, character: 0 };
      errors.push({
        message:
          typeof diag.messageText === "string"
            ? diag.messageText
            : diag.messageText.messageText,
        line: pos.line + 1,
        column: pos.character + 1,
        severity: "error",
      });
    }
  }

  // Don't stop on type errors – the compiler can still generate code for many cases
  // Only stop on syntax errors (parsing failures)
  const hasSyntaxErrors = ast.syntacticDiagnostics.some(
    (d) => d.category === 1 && d.file === ast.sourceFile,
  );

  if (hasSyntaxErrors && errors.length > 0) {
    return {
      binary: new Uint8Array(0),
      wat: "",
      dts: "",
      importsHelper: "",
      success: false,
      errors,
      stringPool: [],
    };
  }

  // Step 2: Generate IR
  let mod;
  try {
    mod = generateModule(ast);
  } catch (e) {
    errors.push({
      message: `Codegen error: ${e instanceof Error ? e.message : String(e)}`,
      line: 0,
      column: 0,
      severity: "error",
    });
    return {
      binary: new Uint8Array(0),
      wat: "",
      dts: "",
      importsHelper: "",
      success: false,
      errors,
      stringPool: [],
    };
  }

  // Step 3: Emit binary
  let binary: Uint8Array;
  try {
    binary = emitBinary(mod);
  } catch (e) {
    errors.push({
      message: `Binary emit error: ${e instanceof Error ? e.message : String(e)}`,
      line: 0,
      column: 0,
      severity: "error",
    });
    return {
      binary: new Uint8Array(0),
      wat: "",
      dts: "",
      importsHelper: "",
      success: false,
      errors,
      stringPool: [],
    };
  }

  // Step 4: Emit WAT (optional)
  let wat = "";
  if (emitWatOutput) {
    try {
      wat = emitWat(mod);
    } catch (e) {
      // WAT emit failure is non-fatal
      errors.push({
        message: `WAT emit warning: ${e instanceof Error ? e.message : String(e)}`,
        line: 0,
        column: 0,
        severity: "warning",
      });
    }
  }

  // Step 5: Generate .d.ts
  const dts = generateDts(ast, mod);

  // Step 6: Generate imports helper
  const importsHelper = generateImportsHelper(mod);

  return {
    binary,
    wat,
    dts,
    importsHelper,
    success: true,
    errors,
    stringPool: mod.stringPool,
  };
}

// ── .d.ts generation ─────────────────────────────────────────────────

function generateDts(ast: TypedAST, mod: WasmModule): string {
  const lines: string[] = ["// Generated by ts2wasm", ""];

  // Exports interface
  const exportLines: string[] = [];
  for (const stmt of ast.sourceFile.statements) {
    if (ts.isFunctionDeclaration(stmt) && stmt.name && hasExportModifier(stmt)) {
      const name = stmt.name.text;
      const params = stmt.parameters
        .map((p) => {
          const paramName = ts.isIdentifier(p.name) ? p.name.text : "_";
          const typeText = mapTypeForDts(p.type, ast.sourceFile);
          const optional = p.questionToken ? "?" : "";
          return `${paramName}${optional}: ${typeText}`;
        })
        .join(", ");
      const returnType = mapTypeForDts(stmt.type, ast.sourceFile);
      exportLines.push(`  ${name}(${params}): ${returnType};`);
    }
  }

  if (exportLines.length > 0) {
    lines.push("export interface Exports {");
    lines.push(...exportLines);
    lines.push("}");
    lines.push("");
  }

  // Build a set of extern class import prefixes for annotation
  const externPrefixes = new Map<string, ExternClassMeta>();
  for (const ec of mod.externClasses) {
    externPrefixes.set(ec.importPrefix, ec);
  }

  // Imports interface — group by module, annotate with comments
  const importsByModule = new Map<string, string[]>();
  for (const imp of mod.imports) {
    if (imp.desc.kind !== "func") continue;
    const typeDef = mod.types[imp.desc.typeIdx] as FuncTypeDef | undefined;
    if (!typeDef) continue;

    const params = typeDef.params
      .map((p, i) => `a${i}: ${wasmTypeToTs(p)}`)
      .join(", ");
    const ret =
      typeDef.results.length === 0
        ? "void"
        : wasmTypeToTs(typeDef.results[0]!);

    // Annotate with comment
    const comment = getImportComment(imp.name, mod);
    const line = comment
      ? `    /** ${comment} */\n    ${imp.name}(${params}): ${ret};`
      : `    ${imp.name}(${params}): ${ret};`;

    const bucket = importsByModule.get(imp.module) ?? [];
    bucket.push(line);
    importsByModule.set(imp.module, bucket);
  }

  if (importsByModule.size > 0) {
    lines.push("export interface Imports {");
    for (const [module, funcs] of importsByModule) {
      const key = module.includes(":") ? `"${module}"` : module;
      const optional = module.startsWith("wasm:") ? "?" : "";
      lines.push(`  ${key}${optional}: {`);
      lines.push(...funcs);
      lines.push("  };");
    }
    lines.push("}");
    lines.push("");
  }

  // Deps interface — what the user must provide for extern classes
  if (mod.externClasses.length > 0) {
    lines.push("/** Dependencies for extern class imports (pass to createImports) */");
    lines.push("export interface Deps {");
    // Group by top-level namespace
    const nsByName = new Map<string, ExternClassMeta[]>();
    for (const ec of mod.externClasses) {
      const ns = ec.namespacePath[0] ?? ec.className;
      const bucket = nsByName.get(ns) ?? [];
      bucket.push(ec);
      nsByName.set(ns, bucket);
    }
    for (const [ns, classes] of nsByName) {
      if (classes.length === 1 && classes[0]!.namespacePath.length === 0) {
        // Top-level class, no namespace wrapper
        lines.push(`  ${ns}: any;`);
      } else {
        lines.push(`  ${ns}: {`);
        for (const ec of classes) {
          const path = ec.namespacePath.slice(1);
          if (path.length === 0) {
            lines.push(`    ${ec.className}: any;`);
          } else {
            lines.push(`    // ${[...path, ec.className].join(".")}`);
            // Emit nested path as a comment — actual value is deeply nested
            lines.push(`    ${ec.className}: any;`);
          }
        }
        lines.push("  };");
      }
    }
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

function getImportComment(name: string, mod: WasmModule): string | undefined {
  // String literal thunks
  const strValue = mod.stringLiteralValues.get(name);
  if (strValue !== undefined) {
    return `returns ${JSON.stringify(strValue)}`;
  }
  // Extern class imports
  for (const ec of mod.externClasses) {
    const prefix = ec.importPrefix;
    if (name === `${prefix}_new`) {
      return `new ${ec.namespacePath.join(".")}.${ec.className}(...)`;
    }
    for (const [methodName] of ec.methods) {
      if (name === `${prefix}_${methodName}`) {
        return `instance.${methodName}(...)`;
      }
    }
    for (const [propName, propInfo] of ec.properties) {
      if (name === `${prefix}_get_${propName}`) {
        return `instance.${propName} (getter)`;
      }
      if (name === `${prefix}_set_${propName}`) {
        return `instance.${propName} = value (setter)`;
      }
    }
  }
  // Math host imports
  if (name.startsWith("Math_")) {
    return `Math.${name.slice(5)}`;
  }
  return undefined;
}

// ── Imports helper generation ────────────────────────────────────────

function generateImportsHelper(mod: WasmModule): string {
  const lines: string[] = [
    "// Generated by ts2wasm — runtime imports helper",
    "// Usage: const imports = createImports(deps);",
    "//        const { instance } = await WebAssembly.instantiateStreaming(fetch('module.wasm'), imports);",
    "",
  ];

  // Determine what we need
  const hasDeps = mod.externClasses.length > 0;
  const hasStringPool = mod.stringPool.length > 0;
  const hasJsString = mod.imports.some((i) => i.module === "wasm:js-string");
  const hasCallbacks = mod.imports.some((i) => i.name === "__make_callback");

  // Late-binding variable for callback support
  if (hasCallbacks) {
    lines.push("let wasmExports;");
    lines.push("export function setExports(exports) { wasmExports = exports; }");
    lines.push("");
  }

  // Function signature
  lines.push(`export function createImports(${hasDeps ? "deps" : ""}) {`);

  // env object
  lines.push("  const env = {");

  for (const imp of mod.imports) {
    if (imp.module !== "env") continue;
    if (imp.desc.kind !== "func") continue;

    const line = generateEnvImportLine(imp.name, mod);
    lines.push(`    ${line},`);
  }

  lines.push("  };");

  // wasm:js-string polyfill
  if (hasJsString) {
    lines.push("");
    lines.push("  // Polyfill for engines without native wasm:js-string support");
    lines.push("  const jsString = {");
    lines.push("    concat: (a, b) => a + b,");
    lines.push("    length: (s) => s.length,");
    lines.push("    equals: (a, b) => a === b ? 1 : 0,");
    lines.push("    substring: (s, start, end) => s.substring(start, end),");
    lines.push("    charCodeAt: (s, i) => s.charCodeAt(i),");
    lines.push("  };");
  }

  // Return statement
  lines.push("");
  if (hasJsString) {
    lines.push('  return { env, "wasm:js-string": jsString };');
  } else {
    lines.push("  return { env };");
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function generateEnvImportLine(name: string, mod: WasmModule): string {
  // String literal thunks
  const strValue = mod.stringLiteralValues.get(name);
  if (strValue !== undefined) {
    return `${name}: () => ${JSON.stringify(strValue)}`;
  }

  // Console stubs
  if (name === "console_log_number") return "console_log_number: (v) => console.log(v)";
  if (name === "console_log_bool") return "console_log_bool: (v) => console.log(Boolean(v))";
  if (name === "console_log_string") return "console_log_string: (v) => console.log(v)";
  if (name === "console_log_externref") return "console_log_externref: (v) => console.log(v)";

  // Primitive method imports
  if (name === "number_toString") return "number_toString: (v) => String(v)";

  // String method imports
  if (name.startsWith("string_")) {
    const method = name.slice(7);
    return `${name}: (s, ...a) => s.${method}(...a)`;
  }

  // Math host imports
  if (name.startsWith("Math_")) {
    const method = name.slice(5);
    return `${name}: Math.${method}`;
  }

  // Extern class imports
  for (const ec of mod.externClasses) {
    const prefix = ec.importPrefix;
    const nsAccess = ec.namespacePath.length > 0
      ? `deps.${ec.namespacePath.join(".")}`
      : `deps`;

    if (name === `${prefix}_new`) {
      const paramList = ec.constructorParams.map((_, i) => `a${i}`).join(", ");
      return `${name}: (${paramList}) => new ${nsAccess}.${ec.className}(${paramList})`;
    }
    for (const [methodName, sig] of ec.methods) {
      if (name === `${prefix}_${methodName}`) {
        const paramList = sig.params.slice(1).map((_, i) => `a${i}`).join(", ");
        return `${name}: (self${paramList ? ", " + paramList : ""}) => self.${methodName}(${paramList})`;
      }
    }
    for (const [propName, propInfo] of ec.properties) {
      if (name === `${prefix}_get_${propName}`) {
        return `${name}: (self) => self.${propName}`;
      }
      if (name === `${prefix}_set_${propName}`) {
        return `${name}: (self, v) => { self.${propName} = v; }`;
      }
    }
  }

  // __make_callback: late-binding wrapper
  if (name === "__make_callback") {
    return `${name}: (id) => (...args) => wasmExports[\`__cb_\${id}\`](...args)`;
  }

  // Fallback: no-op stub
  return `${name}: () => {}`;
}

function mapTypeForDts(
  typeNode: ts.TypeNode | undefined,
  sf: ts.SourceFile,
): string {
  if (!typeNode) return "void";
  const text = typeNode.getText(sf);
  if (
    text === "number" ||
    text === "boolean" ||
    text === "string" ||
    text === "void"
  ) {
    return text;
  }
  return "any";
}

function wasmTypeToTs(type: ValType): string {
  switch (type.kind) {
    case "f64":
      return "number";
    case "i32":
      return "number";
    case "externref":
      return "any";
    default:
      return "any";
  }
}

function hasExportModifier(node: ts.Node): boolean {
  const modifiers = ts.canHaveModifiers(node)
    ? ts.getModifiers(node)
    : undefined;
  return (
    modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword) ?? false
  );
}
