import ts from "typescript";
import { analyzeSource, type TypedAST } from "./checker/index.js";
import { generateModule } from "./codegen/index.js";
import { emitBinary } from "./emit/binary.js";
import { emitWat } from "./emit/wat.js";
import { preprocessImports } from "./import-resolver.js";
import type {
  CompileResult,
  CompileError,
  CompileOptions,
} from "./index.js";
import type { WasmModule, FuncTypeDef, ValType } from "./ir/types.js";

/**
 * Orchestrates the full compilation pipeline:
 * TS Source → tsc Parser+Checker → Codegen → Binary + WAT
 */
export function compileSource(
  source: string,
  options: CompileOptions = {},
): CompileResult {
  const errors: CompileError[] = [];
  const emitWatOutput = options.emitWat !== false;

  // Step 0: Pre-process imports (replace import * as X with declare namespace)
  const processedSource = preprocessImports(source);

  // Step 1: Parse and type-check
  const ast = analyzeSource(processedSource, options.moduleName ?? "input.ts");

  // Collect TS diagnostics as errors
  for (const diag of ast.diagnostics) {
    if (diag.category === 1) {
      // Error
      const pos = diag.file
        ? diag.file.getLineAndCharacterOfPosition(diag.start ?? 0)
        : { line: 0, character: 0 };
      errors.push({
        message:
          typeof diag.messageText === "string"
            ? diag.messageText
            : diag.messageText.messageText,
        line: pos.line + 1,
        column: pos.character + 1,
        severity: "error",
      });
    }
  }

  // Don't stop on type errors – the compiler can still generate code for many cases
  // Only stop on syntax errors (parsing failures)
  const hasSyntaxErrors = ast.syntacticDiagnostics.some(
    (d) => d.category === 1 && d.file === ast.sourceFile,
  );

  if (hasSyntaxErrors && errors.length > 0) {
    return {
      binary: new Uint8Array(0),
      wat: "",
      dts: "",
      success: false,
      errors,
      stringPool: [],
    };
  }

  // Step 2: Generate IR
  let mod;
  try {
    mod = generateModule(ast);
  } catch (e) {
    errors.push({
      message: `Codegen error: ${e instanceof Error ? e.message : String(e)}`,
      line: 0,
      column: 0,
      severity: "error",
    });
    return {
      binary: new Uint8Array(0),
      wat: "",
      dts: "",
      success: false,
      errors,
      stringPool: [],
    };
  }

  // Step 3: Emit binary
  let binary: Uint8Array;
  try {
    binary = emitBinary(mod);
  } catch (e) {
    errors.push({
      message: `Binary emit error: ${e instanceof Error ? e.message : String(e)}`,
      line: 0,
      column: 0,
      severity: "error",
    });
    return {
      binary: new Uint8Array(0),
      wat: "",
      dts: "",
      success: false,
      errors,
      stringPool: [],
    };
  }

  // Step 4: Emit WAT (optional)
  let wat = "";
  if (emitWatOutput) {
    try {
      wat = emitWat(mod);
    } catch (e) {
      // WAT emit failure is non-fatal
      errors.push({
        message: `WAT emit warning: ${e instanceof Error ? e.message : String(e)}`,
        line: 0,
        column: 0,
        severity: "warning",
      });
    }
  }

  // Step 5: Generate .d.ts
  const dts = generateDts(ast, mod);

  return {
    binary,
    wat,
    dts,
    success: true,
    errors,
    stringPool: mod.stringPool,
  };
}

// ── .d.ts generation ─────────────────────────────────────────────────

function generateDts(ast: TypedAST, mod: WasmModule): string {
  const lines: string[] = ["// Generated by ts2wasm", ""];

  // Exports interface
  const exportLines: string[] = [];
  for (const stmt of ast.sourceFile.statements) {
    if (ts.isFunctionDeclaration(stmt) && stmt.name && hasExportModifier(stmt)) {
      const name = stmt.name.text;
      const params = stmt.parameters
        .map((p) => {
          const paramName = ts.isIdentifier(p.name) ? p.name.text : "_";
          const typeText = mapTypeForDts(p.type, ast.sourceFile);
          const optional = p.questionToken ? "?" : "";
          return `${paramName}${optional}: ${typeText}`;
        })
        .join(", ");
      const returnType = mapTypeForDts(stmt.type, ast.sourceFile);
      exportLines.push(`  ${name}(${params}): ${returnType};`);
    }
  }

  if (exportLines.length > 0) {
    lines.push("export interface Exports {");
    lines.push(...exportLines);
    lines.push("}");
    lines.push("");
  }

  // Imports interface
  const importsByModule = new Map<string, string[]>();
  for (const imp of mod.imports) {
    if (imp.desc.kind !== "func") continue;
    const typeDef = mod.types[imp.desc.typeIdx] as FuncTypeDef | undefined;
    if (!typeDef) continue;

    const params = typeDef.params
      .map((p, i) => `a${i}: ${wasmTypeToTs(p)}`)
      .join(", ");
    const ret =
      typeDef.results.length === 0
        ? "void"
        : wasmTypeToTs(typeDef.results[0]!);

    const bucket = importsByModule.get(imp.module) ?? [];
    bucket.push(`    ${imp.name}(${params}): ${ret};`);
    importsByModule.set(imp.module, bucket);
  }

  if (importsByModule.size > 0) {
    lines.push("export interface Imports {");
    for (const [module, funcs] of importsByModule) {
      const key = module.includes(":") ? `"${module}"` : module;
      lines.push(`  ${key}: {`);
      lines.push(...funcs);
      lines.push("  };");
    }
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

function mapTypeForDts(
  typeNode: ts.TypeNode | undefined,
  sf: ts.SourceFile,
): string {
  if (!typeNode) return "void";
  const text = typeNode.getText(sf);
  if (
    text === "number" ||
    text === "boolean" ||
    text === "string" ||
    text === "void"
  ) {
    return text;
  }
  return "any";
}

function wasmTypeToTs(type: ValType): string {
  switch (type.kind) {
    case "f64":
      return "number";
    case "i32":
      return "number";
    case "externref":
      return "any";
    default:
      return "any";
  }
}

function hasExportModifier(node: ts.Node): boolean {
  const modifiers = ts.canHaveModifiers(node)
    ? ts.getModifiers(node)
    : undefined;
  return (
    modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword) ?? false
  );
}
